clusterId: 'Local'
clusterName: 'Rotr-Local'
dataDir: '/tmp/rotr'
tick: 1000
nodes:
  - id: 'rotr.1'
    host: '0.0.0.0'
    rotrPort: 19831
    replicationPort: 36001
    electionPort: 36010
  - id: 'rotr.2'
    host: '0.0.0.0'
    rotrPort: 19832           # To be same as previous node when all nodes are not running on the same machine
    replicationPort: 36002    # To be same as previous node when all nodes are not running on the same machine
    electionPort: 36020       # To be same as previous node when all nodes are not running on the same machine
  - id: 'rotr.3'
    host: '0.0.0.0'
    rotrPort: 19833           # To be same as previous node when all nodes are not running on the same machine
    replicationPort: 36003    # To be same as previous node when all nodes are not running on the same machine
    electionPort: 36030       # To be same as previous node when all nodes are not running on the same machine
